spring:
  profiles:
    active: ${APP_PROFILE:local}
  jpa:
    open-in-view: false

api:
  security:
    token:
      expiration: 600
      issuer: honey-api-playground
      secret: ${JWT_SECRET:my-default-secret-key}
