spring:
  profiles:
    active: ${APP_PROFILE:local}
  jpa:
    open-in-view: false

api:
  security:
    token:
      issuer: honey-api-playground
      secret: ${JWT_SECRET:my-default-honey-secret-key}
      expiration:
        in:
          seconds: 600
