spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/honey-api-playground?createDatabaseIfNotExist=true
    username: postgres
    password: root123

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

        jdbc:
          lob:
            non_contextual_creation: true

    hibernate:
      dll-auto: update
