spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    data: classpath:data-local.sql

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      dll-auto: create

    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: false

    properties:
      hibernate:
        format_sql: true
